### ISSUE TITLE
Install Manual / App not starting

### ISSUE THREAD

**Issue by peschu123** [WillKoehrsen/Bokeh-Python-Visualization#1]
Hi Will,
I saw your post on medium and just wanted to take a quick look, before diving deeper. :)
So I cloned your project and installed missing dependencies, but it is not starting? A requirements file would be nice too.

Mabye you have an idea why it is not starting. 
Tried with python 3.65 (latest) on Win10 to start via "bokeh_app\main.py".

It looks like it starts and then gives me back the command prompt without any error message. I normally don't use python, so maybe I'm the issue. ;-)

KR,

Peter

**Comment by WillKoehrsen** [comment]
Sorry about the lack of documentation! I'll get working on that right now. Did you try running `bokeh serve --show bokeh_app/`? That's the syntax to run a Bokeh server from the command line.

**Comment by peschu123** [comment]
No I didn't try it that way.  Maybe that was the missing part, hopefully this will help someone. I tried dash afterwards which worked flawlessly for me... sorry ;-)
